name: test ubuntulatest pythonlatest

on:
  workflow_dispatch:

jobs:
  full_test:       
    runs-on: 'ubuntu-22.04'
    name: test package with ubuntu22.04 et python3.11
    steps:
      #preparation
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: x64                            
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      #installation          
      - name: install ytdlmusic
        run: |
          pip install .
      - name : list package
        run: pip list --format=columns    
      #test 1
      - name: Launch minimal test
        uses: ./.github/actions/minimal_test 
      #configuration
      - name: install ffmpeg with token
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      #test 2    
      - name: Launch full test
        uses: ./.github/actions/full_test
    
